# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a369e7e20bca44396d01bd1b80881ee55bfd4d9a0cb3bad0d670cbc2de21cf641289759339a2803a69ed3fcf66bff37ab6aec90f7756f7306a557c01f5e16cf2

test:
  secret_key_base: 3372ec73f4987dfc0e560d0fd8da16ff38212de07f2f9f88585daeaa5a0c85381901235e1e163e76e21f95ad7bd8e1ad1f8c292082c47c03b5b5e1fd43595c21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
